apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: vision-campus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vision-campus-service
            port:
              number: 80
